//
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: test.proto

// Package testdata contains generated code for test.proto. Generated by
// protocol compiler protoc.
//
// Note that when compiling the library with Bazel, the Go source code is
// generated automatically from test.proto, and this file is not used. This
// file is used when the library is compiled by some other means, for example
// with the "go" tool (i.e., "go build").
package testdata

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestAnon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foo *int64  `protobuf:"varint,1,opt,name=foo" json:"foo,omitempty"`
	Bar *string `protobuf:"bytes,2,opt,name=bar" json:"bar,omitempty"`
}

func (x *TestAnon) Reset() {
	*x = TestAnon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestAnon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAnon) ProtoMessage() {}

func (x *TestAnon) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAnon.ProtoReflect.Descriptor instead.
func (*TestAnon) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestAnon) GetFoo() int64 {
	if x != nil && x.Foo != nil {
		return *x.Foo
	}
	return 0
}

func (x *TestAnon) GetBar() string {
	if x != nil && x.Bar != nil {
		return *x.Bar
	}
	return ""
}

type TestComplex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Simple    *string                   `protobuf:"bytes,1,opt,name=simple" json:"simple,omitempty"`
	Empty     *string                   `protobuf:"bytes,2,opt,name=empty" json:"empty,omitempty"`
	Repeat    []string                  `protobuf:"bytes,3,rep,name=repeat" json:"repeat,omitempty"`
	Sub       *TestComplex_Submessage   `protobuf:"bytes,4,opt,name=sub" json:"sub,omitempty"`
	Subrepeat []*TestComplex_Submessage `protobuf:"bytes,5,rep,name=subrepeat" json:"subrepeat,omitempty"`
}

func (x *TestComplex) Reset() {
	*x = TestComplex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestComplex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestComplex) ProtoMessage() {}

func (x *TestComplex) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestComplex.ProtoReflect.Descriptor instead.
func (*TestComplex) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestComplex) GetSimple() string {
	if x != nil && x.Simple != nil {
		return *x.Simple
	}
	return ""
}

func (x *TestComplex) GetEmpty() string {
	if x != nil && x.Empty != nil {
		return *x.Empty
	}
	return ""
}

func (x *TestComplex) GetRepeat() []string {
	if x != nil {
		return x.Repeat
	}
	return nil
}

func (x *TestComplex) GetSub() *TestComplex_Submessage {
	if x != nil {
		return x.Sub
	}
	return nil
}

func (x *TestComplex) GetSubrepeat() []*TestComplex_Submessage {
	if x != nil {
		return x.Subrepeat
	}
	return nil
}

type TestComplex_Submessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Simple *string  `protobuf:"bytes,1,opt,name=simple" json:"simple,omitempty"`
	Repeat []string `protobuf:"bytes,2,rep,name=repeat" json:"repeat,omitempty"`
}

func (x *TestComplex_Submessage) Reset() {
	*x = TestComplex_Submessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestComplex_Submessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestComplex_Submessage) ProtoMessage() {}

func (x *TestComplex_Submessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestComplex_Submessage.ProtoReflect.Descriptor instead.
func (*TestComplex_Submessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1, 0}
}

func (x *TestComplex_Submessage) GetSimple() string {
	if x != nil && x.Simple != nil {
		return *x.Simple
	}
	return ""
}

func (x *TestComplex_Submessage) GetRepeat() []string {
	if x != nil {
		return x.Repeat
	}
	return nil
}

var File_test_proto protoreflect.FileDescriptor

var file_test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x29, 0x64, 0x69,
	0x66, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x63, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x5f, 0x6f, 0x6e, 0x5f, 0x62, 0x65,
	0x61, 0x6d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x41,
	0x6e, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x66, 0x6f, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x62, 0x61, 0x72, 0x22, 0xc7, 0x02, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x12, 0x53, 0x0a,
	0x03, 0x73, 0x75, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x64, 0x69, 0x66,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63,
	0x79, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x5f, 0x6f, 0x6e, 0x5f, 0x62, 0x65, 0x61,
	0x6d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x78, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x73,
	0x75, 0x62, 0x12, 0x5f, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x64, 0x69, 0x66, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x63, 0x79, 0x5f, 0x6f, 0x6e, 0x5f, 0x62, 0x65, 0x61, 0x6d, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x2e, 0x53, 0x75,
	0x62, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x09, 0x73, 0x75, 0x62, 0x72, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x1a, 0x3c, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x64, 0x69, 0x66, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x2d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2f, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x63, 0x79, 0x2d, 0x6f, 0x6e, 0x2d, 0x62, 0x65, 0x61, 0x6d, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x64, 0x61, 0x74, 0x61,
}

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData = file_test_proto_rawDesc
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_rawDescData)
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_proto_goTypes = []interface{}{
	(*TestAnon)(nil),               // 0: differential_privacy.privacy_on_beam.test.TestAnon
	(*TestComplex)(nil),            // 1: differential_privacy.privacy_on_beam.test.TestComplex
	(*TestComplex_Submessage)(nil), // 2: differential_privacy.privacy_on_beam.test.TestComplex.Submessage
}
var file_test_proto_depIdxs = []int32{
	2, // 0: differential_privacy.privacy_on_beam.test.TestComplex.sub:type_name -> differential_privacy.privacy_on_beam.test.TestComplex.Submessage
	2, // 1: differential_privacy.privacy_on_beam.test.TestComplex.subrepeat:type_name -> differential_privacy.privacy_on_beam.test.TestComplex.Submessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestAnon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestComplex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestComplex_Submessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_rawDesc = nil
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
