# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Configuration file for the Sphinx documentation builder."""

import os
import sys

# Add the directory containing the package to sys.path
sys.path.insert(0, os.path.abspath('..'))


def _get_version():
  """Parses the version number from VERSION file."""
  here = os.path.dirname(os.path.abspath(__file__))
  version_file = os.path.join(here, '..', 'VERSION')
  with open(version_file) as f:
    try:
      version_line = next(line for line in f if not line.startswith('"""'))
    except StopIteration as exc:
      raise ValueError('Version not defined in VERSION') from exc
    else:
      return version_line.strip('\n \'"')


# -- Project information -----------------------------------------------------

project = 'dp-accounting'
copyright = '2026, Google LLC'  # pylint: disable=redefined-builtin
author = 'Google Differential Privacy Team'
release = _get_version()

# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.napoleon',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    'myst_parser',
    'sphinx_autodoc_typehints',
]

autosummary_generate = True

# Configure autodoc settings
default_role = 'literal'
autodoc_typehints = 'signature'
autoclass_content = 'both'
autodoc_member_order = 'bysource'
napoleon_use_ivar = True

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'


def remove_attrs_docstrings(app, what, name, obj, options, lines):
  del app, what, name, obj, options  # Unused.
  filtered = [
      line
      for line in lines
      if 'Method generated by attrs for class' not in line
  ]
  lines.clear()
  lines.extend(filtered)


def setup(app):
  app.connect('autodoc-process-docstring', remove_attrs_docstrings)
