#
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

workspace(name = "dp_auditorium_py")

load("@dp_auditorium_py//:dp_auditorium_py_deps.bzl", "dp_auditorium_py_deps")

dp_auditorium_py_deps()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@dp_auditorium_py//:dp_auditorium_py_deps_init.bzl", "dp_auditorium_py_deps_init")

dp_auditorium_py_deps_init("dp_auditorium_py")

load("@dp_auditorium_py_pip_deps//:requirements.bzl", "install_deps")

install_deps()
