#
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

workspace(name = "learning")

load("@learning//:learning_py_deps.bzl", "learning_py_deps")

learning_py_deps()

load("@learning//:learning_py_deps_init.bzl", "learning_py_deps_init")

learning_py_deps_init("learning")

local_repository(
    name = "com_google_python_dp_accounting",
    path = "../python/dp_accounting/",
)

load("@com_google_python_dp_accounting//:accounting_py_deps.bzl", "accounting_py_deps")

accounting_py_deps()

load("@com_google_python_dp_accounting//:accounting_py_deps_init.bzl", "accounting_py_deps_init")

accounting_py_deps_init("com_google_python_dp_accounting")
